### DISCUSSION TITLE
include not working

### DISCUSSION THREAD

**Discussion by mosandlt** [hassio-addons/addon-influxdb#381] [Q&A]
Hello,
i configured my include and normally everything should be excluded. somehow this is not working.

Also, the question is how I can remove all data which are not contained within the include?
```
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.rct_power_storage_all_generators_power
      - sensor.rct_power_storage_consumer_power
      - sensor.rct_power_storage_grid_power
      - sensor.rct_power_storage_battery_power
      - sensor.rct_power_storage_battery_charge_capacity
      - sensor.rct_power_storage_battery_voltage
      - sensor.autarkiegrad_monat
      - sensor.autarkiegrad_heute
      - sensor.autarkiegrad_jahr
      - sensor.autarkiegrad_total
      - sensor.system_pressure
    entity_globs:
      - .*temp*
      - .*humi*
      - valve.*


```
