### ISSUE TITLE
Ability to specify/override retention policy the HA influxdb component

### ISSUE THREAD

**Issue by isorin** [hassio-addons/addon-influxdb#138]
# Problem/Motivation

Reopening of https://github.com/hassio-addons/addon-influxdb/issues/123

## Expected behavior

The ability to specify/override which retention policy the HA influxdb component writes data to.
Retention policies define how long data is stored in a database, each measurement can have data in one or more retention policies.
We need the ability to control in which retention policy data is stored for each individual measurement.
CQ in influxdb always downsamples data and this might not be the desired action for data which doesn't need it.

## Actual behavior

HA influxdb component only writes data to the default retention policy for all measurements.

## Steps to reproduce

N/A

## Proposed changes

A few examples:
```
component_config_domain:
  climate:
    override_measurement: climate
    override_retention_policy: rp_90days

component_config_glob:
  sensor.*thermostat*:
    override_measurement: thermostat
    override_retention_policy: longterm

Another form, which uses influxdb syntax <retention_policy>.<measurement> could be:

component_config_glob:
  sensor.*thermostat*:
    override_measurement: longterm.thermostat
```
