### ISSUE TITLE
Request for Data disk usage sensor

### ISSUE THREAD

**Issue by erkr** [hassio-addons/addon-influxdb#226]
# Problem/Motivation

I run InfluxDB as add on and can’t monitor the actual data storage size. Tried an influxDB sensor like this one:
```
  queries:
      - name: InfluxDB Size
        unit_of_measurement: MB
        value_template: '{{ (value | float(0) / 1024 /1024) | round(1) }}'
        group_function: mean
        measurement: '"monitor"."shard"'
        database: _internal
        where: 'time > now() - 1m AND "database"=''homeassistant'''
        field: diskBytes 
  - 
```
This sensor seems to give the current shard size, but not the total influxDB data disk usage.

## Expected behavior

Please add a sensor that provides this information. Regards Eric

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
