### ISSUE TITLE
[Help Request] Possible to populate sensors from multiple DBs inside Influx?

### ISSUE THREAD

**Issue by stratus-ss** [hassio-addons/addon-influxdb#238]
# Problem/Motivation

Hi, I currently have devices that are sending information to Influx via Telegraf. I also have the home assistant (hassio) instance configured to be dumping into its own DB inside of Influx (as per the example in the documentation). 

Ideally, I would have sensors coming in from a different DB in Influx so I could take action when some other equipment's temperature rises. It was unclear to me how I might achieve this. Can someone point me down the right path?

Below is the `configuration.yaml`:

```
influxdb:
  host: xxxx-influxdb
  port: 1234
  database: homeassistant
  username: xxxx
  password: xxxx
  max_retries: 3
  default_measurement: state
  component_config:
    counter.hotw:
      override_measurement: lt
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
```
