### ISSUE TITLE
HA Config missing authentication

### ISSUE THREAD

**Issue by sstarcher** [hassio-addons/addon-influxdb#250]
# Problem/Motivation

* Attempted to follow docs to setup HA with InfluxDB and it failed during restart

## Expected behavior

* Metrics flowing

## Actual behavior

Error during restart
```
The system cannot restart because the configuration is not valid: Invalid config for [influxdb]: some but not all values in the same group of inclusion 'authentication' @ data['influxdb'][<authentication>]. Got None. (See /config/configuration.yaml, line 38).
```

## Steps to reproduce

Addon Config
```
auth: true
certfile: fullchain.pem
envvars: []
keyfile: privkey.pem
reporting: true
ssl: true
```

HA Config
```
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
```

Also tried localhost for the host.

## Proposed changes

config to work
