### ISSUE TITLE
InfluxDB host parameter ignored - integration connects to default cloud instance instead

### ISSUE THREAD

**Issue by leogaggl** [hassio-addons/addon-influxdb#267]
# Problem/Motivation

> Trying to connect to an externally hosted InfluxDB (2.6.1) instance over SSL (Port 443).
```
influxdb:
  host: host.example.com
  api_version: 2
  organization: ORGID
  token: APITOKEN
  bucket: bucketname
  verify_ssl: true
```
The config parameters are 100% correct and verified with Postman test.

## Expected behavior

> Connect to the correct instance as per the "host" parameter.

## Actual behavior

> Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='us-west-2-1.aws.cloud2.influxdata.com', port=443): Read timed out. (read timeout=10.0)'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible.
InfluxDB bucket is not accessible due to '(401) Reason: Unauthorized HTTP response headers:

## Steps to reproduce

> this has been consistent. Have tried to move host parameter to first setting
