### ISSUE TITLE
Config Example in Documentation not working

### ISSUE THREAD

**Issue by momonator25** [hassio-addons/addon-influxdb#323]
# Problem/Motivation

I have  spent some time to find out why there is no data saved to influxdb-addon database from HA because the provided example in the documentation ist not correct.

```yaml
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: <yourpassword>
  max_retries: 3
  default_measurement: state
```

## Expected behavior

The host can be copied from the example because it stays the same for all installations.

## Actual behavior

HA could not save data to influxdb.

## Steps to reproduce

1. Install addon-influxdb
2. Create config from example
3. Copy paste the block above in the configuration.yaml (of course change the password)

## Proposed changes

For me the problem was solved with using the IP Address of the HA installation instead of the `a0d7b954-influxdb` string as written [here](https://www.home-assistant.io/integrations/influxdb#host).
