### ISSUE TITLE
Changed DB location seems not to work

### ISSUE THREAD

**Issue by dukemadcat** [hassio-addons/addon-influxdb#327]
# Problem/Motivation

I run home assistant on a Raspberry Pi 5 with limited SD card space and wanted to move the database location to a mounted usb-drive.
I found this [tutorial](https://community.home-assistant.io/t/influxdb-hassio-add-on-changing-default-database-location/172354) and decided to give it a try.
I know it also mentions here that changing environment variables can cause the addon to stop working, but I was hoping someone would still know what I did wrong.

## Expected behavior

I expected *.db files to appear in the locations for "Meta", "Data" and "Wal".

## Actual behavior

No data has yet appeared on the mounted storage, but the database is being filled without changing the storage requirement on the SD card. Is it possible that the data is currently only in RAM?

## Steps to reproduce

1.  I mounted the storage
2. I have created the required folders
3. I have installed the InfluxDB addon
4. I have adjusted the configuration of the addon as follows:
``` yaml
auth: false
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars:
  - name: INFLUXDB_META_DIR
    value: /media/usb-sda5/db/influxdb/meta
  - name: INFLUXDB_DATA_DIR
    value: /media/usb-sda5/db/influxdb/data
  - name: INFLUXDB_WAL_DIR
    value: /media/usb-sda5/db/influxdb/wal
```
5. I added the following in the configuration.yaml:
``` yaml
influxdb:
  username: hainfluxuser
  password: ################
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: state
  exclude:
    entities:
      - zone.home
    domains:
      - persisitant_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
      - sun
      - light
      - cover
    entities:
      - weather.home
```
6. I started the addon
