### ISSUE TITLE
Database host is not accessible due to '401: {"error":"authorization failed"} '

### ISSUE THREAD

**Issue by ciscozine** [hassio-addons/addon-influxdb#34]
Hi to all,
I have updated my hassio server from 0.91.4 to the last version 0.92.2, but now i receive this error from influxdb:

`Database host is not accessible due to '401: {"error":"authorization failed"} ', please check your entries in the configuration file and that the database exists and is READ/WRITE`

my partial configuration.yaml is:

```
influxdb:
  host: 192.168.100.53
  database: Arduino
  username: xxxxxxx
  password: xxxxxxx
  port: 8086
  max_retries: 3
  ssl: false
  verify_ssl: false
  exclude:
    domains:
      - binary_sensor
      - light
      - automation
      - switch
```
	  
	  
```
sensor:
  - platform: influxdb
    queries:
    - name: Temperatura-INT
      unit_of_measurement: °C
      value_template: '{{ value | round(1) }}'
      group_function: last
      where: '"tipo" = ''temperature'' and "device" = ''CC:50:E3:C6:C0:a3'''
      measurement: '"sensori"'
      field: value
      database: Arduino
```

how can I do? If I rollback to the 0.91.4 all works fine

**Comment by ciscozine** [comment]
This is what I see in the hassio log


```
Database host is not accessible due to '401: {"error":"authorization failed"} ', please check your entries in the configuration file and that the database exists and is READ/WRITE
4:41 PM components/influxdb/sensor.py (ERROR) - message first occured at 4:41 PM and shows up 6 times
```

**Comment by ciscozine** [comment]
Find it the solution adding these lines

```
sensor:
  # Weather prediction
  - platform: influxdb
    host: IP
    username: xxxxxxxxxx
    password: xxxxxxxxxx
```
