### ISSUE TITLE
using labels to decide what entities to include?

### ISSUE THREAD

**Issue by strelniece** [hassio-addons/addon-influxdb#343]
A question/suggestion.

But are there any thoughts about using labels as filters for what entities to include?

Just feels so easy to just, for example, add the label influxdb to an entity and not having to hassle with include, exclude combos to get it right.

**Comment by tjorim** [comment]
Not related to this add-on. The influxdb integration pushes the data.

**Comment by strelniece** [comment]
Sorry for late reply, but just want to check I managed to explain properly.
But I think it would make it much easier to filter out what entities to write to influxDB if lables could be used in include/exclude.

So if I add the label "to_influxDB" to the entities I want to write to influxDB, and write the config like:

```
influxdb:
  include:
    domains:
      - alarm_control_panel
      - light
     label:
     - to_influxdb

```
Yes, I have no clue how the lablels are handed in the background by HASS, so maybe it's no possible to use labels in include/exclude, but it would be very handy.
