### ISSUE TITLE
Config error, expected dictionary value

### ISSUE THREAD

**Issue by nvschilleman** [hassio-addons/addon-influxdb#57]
# Problem/Motivation

Keep getting config errors, while my config comparable to examples

## Expected behavior

Including only the set entities to my database

## Actual behavior

Keeps getting errors

I've configured the addon following the steps given in the readme. When trying to configure the component in Hass I keep getting the following errors:

`Invalid config for [influxdb]: expected a dictionary for dictionary value @ data['influxdb']['include']. Got [OrderedDict([('entities', [OrderedDict([('entity', 'binary_sensor.koelsignaal')]), OrderedDict([('entity', 'binary_sensor.compressor')]), OrderedDict([('entity', 'binary_sensor.verdamperventilator')]), OrderedDict([('entity', 'sensor.ontdooiing')]), OrderedDict([('entity', 'binary_sensor.celdeur')]), OrderedDict([('entity', 'binary_sensor.algemene_koelstoring')])])])]. (See /config/configuration.yaml, line 54). Please check the docs at https://home-assistant.io/integrations/influxdb/
`

I don't see anything wrong in my config, this is my config:

```

 influxdb:
   host: a0d7b954-influxdb
   port: 8086
   database: pfio_mon
   username: xxx
   password: xxx
   max_retries: 3
   include:
       entities:
         - binary_sensor.koelsignaal
         - binary_sensor.compressor
         - binary_sensor.verdamperventilator
         - sensor.ontdooiing
         - binary_sensor.celdeur
         - binary_sensor.algemene_koelstoring
   default_measurement: state
   tags: 
     source: hass
```
