### ISSUE TITLE
Binding udp 8089

### ISSUE THREAD

**Issue by pex81** [hassio-addons/addon-influxdb#71]
# Problem/Motivation
i have installed and configure influxdb addon hassio, it works well, if i add the following configuration to listen on udp it doesn't work, is the configuration correct?

```
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars:
  - name: INFLUXDB_UDP_ENABLED
    value: 'true'
  - name: INFLUXDB_UDP_BIND_ADDRESS
    value: ':8089'
  - name: INFLUXDB_UDP_DATABASE
    value: proxmox
  - name: INFLUXDB_UDP_0_BATCH_SIZE
    value: '1000'
  - name: INFLUXDB_UDP_BATCH_TIMEOUT
    value: 1s
log_level: info 
```

> (Why the issue was filed)

## Expected behavior
listening on udp port 8089

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
