### ISSUE TITLE
Very high CPU usage after upgrade to 3.7.1

### ISSUE THREAD

**Issue by L2v2P** [hassio-addons/addon-influxdb#81]
# Problem/Motivation

After I upgraded from version 3.6.2 to 3.7.1 Influxdb started to use a lot of CPU cycles. According to `docker stats` it hits 300% CPU every couple of seconds which basically makes my RPi based HA unusable.

I run Influxdb with the following config (which worked fine up until 3.6.2):

```
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars:
  - name: INFLUXDB_MONITOR_STORE_ENABLED
    value: 'false'
  - name: INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE
    value: 100m
  - name: INFLUXDB_DATA_CACHE_SNAPSHOT_MEMORY_SIZE
    value: 50m
  - name: INFLUXDB_DATA_INDEX_VERSION
    value: tsi1
log_level: debug
```

## Proposed changes

Other than somehow fixing this, can I downgrade Influxdb to 3.6.2 somehow until then? I can't seem to find any instructions on how to do this.
