### ISSUE TITLE
Collectd support (allow 25826 UDP port to the container)

### ISSUE THREAD

**Issue by SebLz** [hassio-addons/addon-influxdb#88]
Collectd listener allows to push detailled systems statistics into the influxdb. It's used for example to monitor OpenWRT routers. 
Currently, only port 8086 of the Influx container is reachable from outside. A new one would be required to leverage the collecd feature of Influxdb. All other Collectd parameters are configurable in the addon configuration page using environnent variables (my config  file as example):

```
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars:
  - name: INFLUXDB_COLLECTD_ENABLED
    value: 'true'
  - name: INFLUXDB_COLLECTD_DATABASE
    value: collectd
  - name: INFLUXDB_COLLECTD_TYPESDB
    value: /data/collectd/types.db
  - name: INFLUXDB_COLLECTD_BIND_ADDRESS
    value: ':25826'
```

This seems related to an older feature request:
https://github.com/hassio-addons/addon-influxdb/issues/1
